# See http://docs.travis-ci.com/user/languages/julia/ and https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Hosting-Documentation-1
# See status of Travis builds at https://travis-ci.org/probcomp/Gen2DAgentMotion.jl

language: julia
julia:
  - 1.5

jobs:
  include:
    - stage: test
      script:
        - julia -e 'using Pkg; Pkg.build(); Pkg.test()'
    - stage: runexample
      script: "JULIA_PROJECT=examples/minimal julia examples/minimal/run.jl"
